version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: neatly-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: neatly-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
